"""
NetSuite ERP adapter — fetches invoices via SuiteQL REST API.

Demo mode (NETSUITE_DEMO_MODE=true):
  No real API calls are made. Returns generated sample invoices so you can
  run the full sync pipeline locally without NetSuite credentials.

Production mode:
  Requires NETSUITE_ACCOUNT_ID, NETSUITE_CLIENT_ID, NETSUITE_CLIENT_SECRET.
  Uses SuiteQL (SQL-like) to query Transaction records with cursor pagination.
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any

import httpx

from ....core.adapter_sdk.erp_adapter import (
    ERPAdapter,
    ERPAdapterConfig,
    FetchResult,
    HealthResult,
    InvoiceFetchOptions,
)
from ....core.adapter_sdk.registry import AdapterRegistry
from ....core.canonical.invoice import (
    CanonicalAddress,
    CanonicalInvoice,
    CanonicalLineItem,
    CanonicalParty,
    InvoiceStatus,
    InvoiceSyncStatus,
)
from .netsuite_auth import NetSuiteAuth, NetSuiteCredentials
from .netsuite_transformer import transform_ns_invoice

logger = logging.getLogger(__name__)

# SuiteQL query — fetches open customer invoices with related fields
_SUITEQL_INVOICES = """
SELECT
  t.id,
  t.tranid,
  t.trandate,
  t.duedate,
  t.memo,
  t.amount,
  t.taxamount,
  t.amountremaining,
  t.status,
  t.entity,
  t.currency,
  t.subsidiary,
  c.entityid  AS entity_name,
  c.email     AS entity_email,
  c.phone     AS entity_phone
FROM Transaction t
JOIN Customer c ON c.id = t.entity
WHERE t.type = 'CustInvc'
  AND t.voided = 'F'
  {where_extra}
ORDER BY t.lastmodifieddate ASC
"""


def _make_demo_invoice(
    tenant_id: str,
    processor_target: str,
    index: int,
) -> CanonicalInvoice:
    """Generate a realistic-looking sample invoice for demo/testing."""
    now = datetime.now(timezone.utc)
    inv_id = f"DEMO-{index:04d}"
    party_id = str(uuid.uuid4())
    company_id = str(uuid.uuid4())

    unit_price = Decimal(f"{100 + index * 25}.00")
    qty = Decimal("2")
    subtotal = (unit_price * qty).quantize(Decimal("0.01"))
    tax = (subtotal * Decimal("0.085")).quantize(Decimal("0.01"))
    total = subtotal + tax

    bill_to = CanonicalParty(
        id=party_id,
        external_id=f"CUST-{index:04d}",
        external_source="netsuite",
        type="customer",
        name=f"Demo Customer {index}",
        email=f"customer{index}@example.com",
        phone="+1-555-000-0001",
        currency="USD",
        billing_address=CanonicalAddress(
            line1=f"{index} Demo Street",
            city="San Jose",
            state="CA",
            postal_code="95110",
            country_code="US",
        ),
    )

    bill_from = CanonicalParty(
        id=company_id,
        external_id="ACME-CORP",
        external_source="netsuite",
        type="vendor",
        name="Acme Corporation",
        email="billing@acme.example.com",
        currency="USD",
        billing_address=CanonicalAddress(
            line1="100 Corporate Way",
            city="San Francisco",
            state="CA",
            postal_code="94102",
            country_code="US",
        ),
    )

    line_items = [
        CanonicalLineItem(
            id=str(uuid.uuid4()),
            line_number=1,
            description=f"Professional Services - Package {index}",
            item_code=f"SVC-{index:03d}",
            quantity=qty,
            unit_price=str(unit_price),
            currency="USD",
            subtotal=str(subtotal),
            total_amount=str(subtotal),
        )
    ]

    return CanonicalInvoice(
        id=str(uuid.uuid4()),
        tenant_id=tenant_id,
        idempotency_key="",  # computed by model_validator
        erp_source="netsuite",
        erp_invoice_id=inv_id,
        erp_invoice_number=f"INV-{now.year}-{index:04d}",
        processor_target=processor_target,
        bill_from=bill_from,
        bill_to=bill_to,
        currency="USD",
        subtotal=str(subtotal),
        total_tax=str(tax),
        total_discount="0.00",
        total_amount=str(total),
        amount_paid="0.00",
        amount_due=str(total),
        line_items=line_items,
        invoice_date=now.strftime("%Y-%m-%d"),
        due_date=now.replace(day=min(now.day + 30, 28)).strftime("%Y-%m-%d"),
        invoice_status=InvoiceStatus.SENT,
        sync_status=InvoiceSyncStatus.PENDING,
        memo=f"Demo invoice {index} generated by invoice-sync-platform",
        metadata={"demo": True, "demo_index": index},
        created_at=now.isoformat(),
        updated_at=now.isoformat(),
    )


class NetSuiteAdapter(ERPAdapter):
    """
    NetSuite ERP adapter.

    Instantiate and register:
        adapter = NetSuiteAdapter(demo_mode=True)
        AdapterRegistry.register_erp(adapter)
    """

    def __init__(self, demo_mode: bool = True):
        self._demo_mode = demo_mode
        self._auth: NetSuiteAuth | None = None
        self._config: ERPAdapterConfig | None = None

    @property
    def adapter_id(self) -> str:
        return "netsuite-v1"

    @property
    def display_name(self) -> str:
        return "NetSuite"

    async def initialize(self, config: ERPAdapterConfig) -> None:
        self._config = config
        if self._demo_mode:
            logger.info("NetSuiteAdapter: demo mode — no real API calls will be made")
            return

        creds = NetSuiteCredentials(
            account_id=config.credentials["account_id"],
            client_id=config.credentials["client_id"],
            client_secret=config.credentials["client_secret"],
        )
        self._auth = NetSuiteAuth(creds)
        # Validate credentials by fetching a token
        await self._auth.get_access_token()
        logger.info("NetSuiteAdapter initialized for account %s",
                    config.credentials["account_id"])

    async def health_check(self) -> HealthResult:
        if self._demo_mode:
            return HealthResult(healthy=True, message="Demo mode — always healthy")
        try:
            assert self._auth is not None
            await self._auth.get_access_token()
            return HealthResult(healthy=True)
        except Exception as exc:
            return HealthResult(healthy=False, message=str(exc))

    async def fetch_invoices(self, opts: InvoiceFetchOptions) -> FetchResult:
        if self._demo_mode:
            return self._fetch_demo_invoices(opts)

        assert self._config is not None and self._auth is not None
        tenant_id = self._config.tenant_id
        processor_target = self._config.options.get("processor_target", "paypal")

        where_parts = []
        if opts.modified_after:
            where_parts.append(f"AND t.lastmodifieddate > TO_DATE('{opts.modified_after}', 'YYYY-MM-DD')")
        if opts.invoice_ids:
            ids = ", ".join(f"'{i}'" for i in opts.invoice_ids)
            where_parts.append(f"AND t.id IN ({ids})")

        query = _SUITEQL_INVOICES.format(where_extra=" ".join(where_parts))
        token = await self._auth.get_access_token()

        params: dict[str, Any] = {"q": query, "limit": opts.limit}
        if opts.cursor:
            params["offset"] = int(opts.cursor)

        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.get(
                f"{self._auth.rest_base}/services/rest/query/v1/suiteql",
                params=params,
                headers={
                    "Authorization": f"Bearer {token}",
                    "Content-Type": "application/json",
                    "Prefer": "transient",
                },
            )
            resp.raise_for_status()
            data = resp.json()

        items: list[dict] = data.get("items", [])
        total = data.get("totalResults", len(items))
        has_more = data.get("hasMore", False)
        next_cursor = str(int(opts.cursor or "0") + len(items)) if has_more else None

        invoices = [
            transform_ns_invoice(item, tenant_id, processor_target)
            for item in items
        ]

        return FetchResult(
            invoices=invoices,
            next_cursor=next_cursor,
            total_count=total,
            has_more=has_more,
        )

    def _fetch_demo_invoices(self, opts: InvoiceFetchOptions) -> FetchResult:
        assert self._config is not None
        tenant_id = self._config.tenant_id
        processor_target = self._config.options.get("processor_target", "paypal")

        start = int(opts.cursor or "0")
        count = min(opts.limit, 5)  # Demo: max 5 invoices per call
        invoices = [
            _make_demo_invoice(tenant_id, processor_target, start + i + 1)
            for i in range(count)
        ]
        # Demo generates exactly 10 total invoices across pages
        has_more = (start + count) < 10
        next_cursor = str(start + count) if has_more else None

        return FetchResult(
            invoices=invoices,
            next_cursor=next_cursor,
            total_count=10,
            has_more=has_more,
        )

    async def fetch_invoice_by_id(self, erp_invoice_id: str) -> CanonicalInvoice | None:
        if self._demo_mode:
            assert self._config is not None
            return _make_demo_invoice(
                self._config.tenant_id,
                self._config.options.get("processor_target", "paypal"),
                index=1,
            )

        assert self._config is not None and self._auth is not None
        token = await self._auth.get_access_token()
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.get(
                f"{self._auth.rest_base}/services/rest/record/v1/invoice/{erp_invoice_id}",
                headers={"Authorization": f"Bearer {token}"},
            )
            if resp.status_code == 404:
                return None
            resp.raise_for_status()

        return transform_ns_invoice(
            resp.json(),
            self._config.tenant_id,
            self._config.options.get("processor_target", "paypal"),
        )

    def transform_to_canonical(self, raw: dict[str, Any]) -> CanonicalInvoice:
        assert self._config is not None
        return transform_ns_invoice(
            raw,
            self._config.tenant_id,
            self._config.options.get("processor_target", "paypal"),
        )


# Self-register when this module is imported
AdapterRegistry.register_erp(NetSuiteAdapter(
    demo_mode=True  # Default; overridden per-tenant via config
))
